# Generated by Django 3.2.3 on 2021-05-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_kospi_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kospi',
            name='image',
        ),
        migrations.AddField(
            model_name='kospi',
            name='imageUrl',
            field=models.TextField(default='/stock/static/img/kospi.png'),
        ),
    ]
