# Generated by Django 3.2.3 on 2021-05-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='keyword',
            field=models.TextField(default='TextField'),
        ),
    ]
